name:                fp2025
version:             0.1.0.0
github:              "vipo/fp-2025"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/fp2025#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - random
    - stm
    - transformers
    - async
    - directory
    - network   # 👈 IMPORTANTE para socket/handle
    - http-client
    - http-client-tls
    - bytestring
    - http-types
    - wai
    - warp

executables:
  fp2025-one:
    main: Main.hs
    source-dirs: app3
    ghc-options:
      - -rtsopts
    dependencies:
      - fp2025
      - repline
      - stm
      - async

  fp2025-server:
    main: server/Main.hs
    source-dirs: app4
    dependencies:
      - fp2025
      - stm
      - network
      - transformers
      - async
      - warp
      - wai
      - http-types
      - bytestring

  fp2025-client:
    main: client/Main.hs
    source-dirs: app4
    dependencies:
      - fp2025
      - network
      - transformers

tests:
  fp2025-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fp2025
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - transformers
      - stm
